[tool.poetry]
name = "pyrenew-covid-wastewater"
version = "0.1.0"
description = ""
authors = ["Damon Bayer <xum8@cdc.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyrenew = {git = "https://github.com/CDCgov/PyRenew"}
ipywidgets = "^8.1.5"
arviz = "^0.19.0"
pyyaml = "^6.0.2"
jupyter = "^1.0.0"
ipykernel = "^6.29.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
